### ISSUE TITLE
apps/greeting  directories not present in project folder tutorial-app (.html containers-tutorial version)

### ISSUE THREAD

**Issue by etherblitzdev** [redhat-scholars/containers-tutorial#15]
apps/greeting   -  Adds Dockerless  (missing directories.)

unable to cd to apps/greeting ( **_project folder_** "**tutorial-app**" directories not present in html containers-tutorial version)
https://redhat-scholars.github.io/containers-tutorial/template-tutorial/dockerless.html#_jib

Luckily I found the directories on an older containers-tutorial github.com repo:
https://github.com/redhat-scholars/containers-tutorial
        apps/greeting    <--  Adds hopefully the possibility to execute Dockerless section...

**Comment by lordofthejars** [comment]
this is how it was supposed to work.

**Comment by etherblitzdev** [comment]
Muchísimas gracias Alex.

Feliz navidad y próspero año nuevo
